version: '3.8'

services:
  app:
    build: .
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}"
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "/bin/sh", "-c", "/app/db-status-check.sh"]
      interval: 10s
      timeout: 30s
      retries: 1
    command: sh -c "./app-startup.sh"

  db:
    image: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
